# Generated by Django 4.2.6 on 2023-11-25 21:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.AutoField(primary_key=True, serialize=False)),
                ('rawname', models.CharField(max_length=255)),
                ('cleanname', models.CharField(max_length=255)),
                ('num', models.CharField(max_length=10)),
                ('publicationdate', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('url_logo', models.TextField()),
                ('url_fandom', models.TextField()),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('url_cover', models.TextField()),
                ('url_read', models.TextField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.series')),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
