# Generated by Django 4.2.1 on 2023-10-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rawname', models.CharField(max_length=255)),
                ('cleanname', models.CharField(max_length=255)),
                ('num', models.CharField(max_length=10)),
                ('publicationdate', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('url_logo', models.TextField()),
                ('url_fandom', models.TextField()),
            ],
        ),
    ]
