# Generated by Django 4.2.1 on 2023-10-26 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('url_cover', models.TextField()),
                ('url_read', models.TextField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.series')),
            ],
        ),
    ]
