# Generated by Django 4.2.6 on 2023-11-23 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='release_date',
            field=models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
    ]
