# Generated by Django 4.2.6 on 2023-11-25 21:19

from django.db import migrations, models
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url_cover', models.TextField()),
                ('release_date', models.DateField()),
                ('url_watch', models.TextField()),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
